---
# AutoBroadcaster (AB) Settings

# Seconds between each message
seconds: 200

# Messages to broadcast
messages:
 - "§e[§aAversion§cAnnouncer§e]§bVote For Our Server To Get Awesome §cRewards!"
 - "§e[§aAversion§cAnnouncer§e]§bHave Fun Playing §aAversion!"
 - "§e[§aAversion§cAnnouncer§e]§bFollow §c@AversionPE §bOn Twitter To Get Updates And Giveaways!"
...
